name: crab
version: 1.0.0
homepage: https://github.com/saccho/crab
description: Provides Rust-like Result and Option types, making it easier to handle error and option values.

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  tuple: ^2.0.0

dev_dependencies:
  pedantic_mono: any
  test: ^1.20.2
