name: Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.dart'
      - 'analysis_options.yaml'
      - 'pubspec.yaml'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - '**.dart'
      - 'analysis_options.yaml'
      - 'pubspec.yaml'
      - '.github/workflows/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart analyze
      - run: dart test
